### ISSUE TITLE
Doesn't report `require.NoError(t , os.Setenv(...))`

### ISSUE THREAD

**Issue by kjaksik** [sivchari/tenv#30]
Tenv doesn't report any issues in such code

```go
func TestLoadConfig(t *testing.T) {
		require.NoError(t, os.Setenv("a", "b"))
}
```

I'd expect it to suggest using `t.Setenv`. Is it the expected behavior here?

**Comment by leonklingele** [comment]
Just stumbled across this one as well. Anyone already working on it? Else I'll give it a try.

**Comment by sivchari** [comment]
Please try it !

**Comment by sivchari** [comment]
@kjaksik 
I handled this case. In the next release, tenv can report the error that you filed.
https://github.com/sivchari/tenv/pull/41
