### ISSUE TITLE
Add support for detecting issues within for loops

### ISSUE THREAD

**Issue by crobert-1** [sivchari/tenv#33]
I added the following test [here](https://github.com/sivchari/tenv/blob/main/testdata/src/a/a_test.go), and no errors or issues are displayed:

```
func TestForLoop(t *testing.T) {
	testsetup()
	for i := 0; i < 3; i++ {
		os.Setenv("a", "b") // want "os\\.Setenv\\(\\) can be replaced by `f\\.Setenv\\(\\)` in TestForLoop"
	}
}
```
The real use case of a `for` loop would most often be a map of `key:value` pairs, but a simple loop exposes the lack of issues being reported.

I believe this should be detected and reported as an error in lint.

**Comment by sivchari** [comment]
Hi, @crobert-1 
Sorry for the late reply. I'll take the time on weekend to fix this problem.

**Comment by sivchari** [comment]
Hi, @coadler .
I supported this case, thanks.

**Comment by crobert-1** [comment]
Thanks @sivchari, really appreciate your help here!
